version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "sparkdb"
      POSTGRES_USER: "spark"
      POSTGRES_PASSWORD: "spark"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local